### ISSUE TITLE
编译后的css能不能不带debug

### ISSUE THREAD

**Issue by kateguan** [songsiqi/px2rem#10]
gulp里面编译出的css能不能不是.debug.css，直接输出.css，remVersion设为false之后直接就不输出css了，是否可以增加个参数需要debug的时候才添加debug

**Comment by gengxuelei** [comment]
用rename重命名
![image](https://cloud.githubusercontent.com/assets/11707936/19752511/835ef794-9c30-11e6-9ff2-9012a8b634fa.png)
参加这里：
https://github.com/gengxuelei/gulp-page/blob/master/gulpfile.js

**Comment by songsiqi** [comment]
@kateguan 在 gulp 环境下可以使用 `postcss-px2rem`
