### ISSUE TITLE
px2rem-loader  不能运用到 vue 文件中，使用时报错

### ISSUE THREAD

**Issue by AnyGong** [songsiqi/px2rem#3]
按照官方的语法推荐，去用，失效。

`[{ test: /\.vue$/, loader: vue.withLoaders({css: 'css!px2rem?remUnit=75&remPrecision=8'})}]`

`ReferenceError: vue is not defined`

**Comment by songsiqi** [comment]
@AnyGong 你用的vue-loader是什么版本？

**Comment by AnyGong** [comment]
@songsiqi 我在这里提了，已解决了我的问题，是因为vue-loader升级的问题  [https://github.com/Jinjiang/px2rem-loader/issues/4](https://github.com/Jinjiang/px2rem-loader/issues/4)，tks！
