### ISSUE TITLE
用-x生成三个版本的css的时候有问题

### ISSUE THREAD

**Issue by Jun90925** [songsiqi/px2rem#8]
第一个是生成了三份css，其实我只想要一份合并的，有大部分的重复代码并不需要分开三份。
第二个是本来是1px的border变成了2px和3px，这不合理……

期待你的回复……

**Comment by songsiqi** [comment]
@Jun90925 

生成3份是旧的方案，现在基本已经不用这种了，使用rem方案生成一份就好，如果要精细控制使用px的话需要加`/*px*/`注释。

1px边框需要加`/*no*/`注释，这样就不会转换了。

详细请看[转换示例](https://www.npmjs.com/package/px2rem#example)

**Comment by Jun90925** [comment]
因为是设计要求，我也没办法。其实我是想把ionic的样式转换过来的，如果要自己去加/_px_/的话，要死……
我已经自己写了一份脚本，勉强弄好了。
谢谢你！
